name: Deploy site to QA bucket

on:
  push:
    branches:
      - main

jobs:

  PROD:
    runs-on: ubuntu-latest
    environment: 
      name: QA
      url: http://acg-staticsitelab-qa-bucket.s3-website.eu-central-1.amazonaws.com  
    env:
      BUCKET_NAME: acg-staticsitelab-qa-bucket
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive --acl public-read